### ISSUE TITLE
Create workspace directory

### ISSUE THREAD

**Issue by exook** [baler-collaboration/baler#111]
Create workspace directory hosting the current projects and data directory to make the docker run command less bloated

**Comment by OliverWoolland** [comment]
Will be working to allow the use of this directory structure

![Untitled presentation](https://user-images.githubusercontent.com/86293426/231724094-c7cf4dad-292d-48d9-8fa8-ba0004ff365b.png)

**Comment by OliverWoolland** [comment]
[Uploading baler.zip…]()
New default zip file for testing
