### ISSUE TITLE
Add docstring to all functions

### ISSUE THREAD

**Issue by exook** [baler-collaboration/baler#120]

**Comment by exook** [comment]
@fritjof-b can we close this? I also closed the "stale functions" issue

**Comment by fritjof-b** [comment]
There's still a lot of type hints and docstrings missing I think. It's hard to add type hinting to functions you didn't write yourself. We could close this and open issues based on which file it concerns instead. It would be a more transparent way than this global issue.

**Comment by exook** [comment]
During the hackathon we added a lot of docstrings. I added two more and it looks like all functions have them now. I will make a separate issue for type hinting
