### ISSUE TITLE
feedback on contributing guidelines

### ISSUE THREAD

**Issue by fritjof-b** [baler-collaboration/baler#135]
I've written a simple contribution guide located [here](https://github.com/baler-compressor/baler/blob/main/documentation/CONTRIBUTING.md).

Would love some feedback and thoughts!

**Comment by exook** [comment]
@fritjof-b Can you add a link to the contributing guidelines in the README and then close this issue. I've reviewed the guidelines and I think they look good :)

**Comment by fritjof-b** [comment]
See #228
