### ISSUE TITLE
Add the CMS example to the tests

### ISSUE THREAD

**Issue by exook** [baler-collaboration/baler#158]
Do a full run of the CMS example as part of the tests and compare the chi^2 of all 24 variables

**Comment by fritjof-b** [comment]
It depends on the definition of done. As we discussed with Oliver, it's not certain that we automatically want to push a Docker image based on a test. Currently, the actions specified when pushing/PR is to train, compress and decompress. If you're happy with that, feel free to close.

**Comment by fritjof-b** [comment]
I'm closing this after our conversation today. Feel free to re-open if you disagree.
