### ISSUE TITLE
Decide GeV cuts for pt & mass

### ISSUE THREAD

**Issue by gallenaxel** [baler-collaboration/baler#162]
How small GeV values should we accept in the pre processing for the particle physics data? Some issues caused with the response for values very close to zero leading to responses of order 10^6 GeV.

**Comment by exook** [comment]
@gallenaxel Can you post the answer as a comment and we can close?

**Comment by gallenaxel** [comment]
The cuts decided upon are:

- For mass: 1 MeV
- For p_T: 1 GeV 

Closing the issue with this comment.
