### ISSUE TITLE
numpy data for example_CMS not present on main or dev

### ISSUE THREAD

**Issue by fritjof-b** [baler-collaboration/baler#169]
As the title says, when trying to run the project through 

```
poetry run python baler --mode=train --project=example_CMS
```

It fails with  `FileNotFoundError: [Errno 2] No such file or directory: 'data/example_CMS/example_CMS_data.npy'`. Should this be the case, or do I need to fetch this file myself? @exook 

This is relevant in context of #158 as well.

**Comment by gallenaxel** [comment]
Avaliable now, so I'll close this issue
