### ISSUE TITLE
Create feature to choose loss functions

### ISSUE THREAD

**Issue by gallenaxel** [baler-collaboration/baler#207]
Currently the choice of loss function is hard-coded. Create a way to change these via the config file.

**Comment by fritjof-b** [comment]
I think this should be done through the CLI. We can discuss it.

**Comment by exook** [comment]
I think picking of loss function belongs in the configuration file. This is better for reproducibility as everything is contained in the config. We could consider using number of epochs in the CLI

**Comment by gallenaxel** [comment]
Merged into `development` with PR #213. Closing issues with this comment.
