### ISSUE TITLE
Create intel, non-gpu Docker image

### ISSUE THREAD

**Issue by OliverWoolland** [baler-collaboration/baler#208]

**Comment by exook** [comment]
Due to easter we didn't meet this week, how is this going? :)

**Comment by OliverWoolland** [comment]
Well I tried approximately 1 million solutions with nothing working particularly well! There seems to be a bit of inherent conflict between how pytorch is distributed and how poetry wants to work. 

In the end I went for something **brutally** simple: [here](https://github.com/baler-collaboration/baler/compare/main...111-create-workspace-directory)

**Comment by OliverWoolland** [comment]
Created a [PR](https://github.com/baler-collaboration/baler/compare/main...111-create-workspace-directory) to main as development seemed both to be behind main and also didn't work for me when I pulled
