### ISSUE TITLE
Check GPU performance

### ISSUE THREAD

**Issue by exook** [baler-collaboration/baler#217]
Do a quick time comparison to verify that the GPU implementation works

**Comment by jayachandru001** [comment]
@exook claim

**Comment by exook** [comment]
In what time span can we expect an update on the findings?

**Comment by exook** [comment]
A friend of mine in Combustion Physics here in Lund ran Baler on his desktop with a RTX 3060 GPU and obtained the following training times:

**CFD 200 epochs:**
CPU: 5.2 min
GPU: 0.375 min

**CMS 25 epochs:**
CPU: 29.7 min
GPU: 1.73 min

This means that with a GPU, the training is 14 times faster for CFD and 17 times faster for HEP data
