### ISSUE TITLE
Create CFD time series

### ISSUE THREAD

**Issue by exook** [baler-collaboration/baler#229]
Create a turbulent flow simulation, as small as possible in (X, Y), for 60 time steps (4 seconds)

**Comment by martacamps** [comment]
I created a 50 x 50 domain of flow around a square and selected 60 time steps of the x component of the flow velocity to create an .npz ready to be compress using Baler. 

The animation below shows the x component of the flow velocity during the 60 time steps. 

![CFDAnimation](https://user-images.githubusercontent.com/15945173/231444354-2250c7b8-cc12-4143-a696-bef01f323f00.gif)

Links to the data: 
[.npz file](https://www.dropbox.com/s/mn56ydyvgt6m7xv/CFDAnimation.npz?dl=0)
[Pre-process file](https://www.dropbox.com/s/dpaka85kk4b16z7/CFDAnimation_preprocess.py?dl=0). It reads the CFD data, creates the .npz file and the .gif animation.

**Comment by exook** [comment]
This is great Marta, thank you!
