### ISSUE TITLE
compression_ratio_bug

### ISSUE THREAD

**Issue by exook** [baler-collaboration/baler#261]
**Describe the bug**
Conversion from config.compression_ratio to the number of columns is wrong

**To Reproduce**
Running example_CMS with a compression ratio of 1.6 should give a latent space with 15 columns, but actually gives 14

**Additional context**
This is caused by machine precision in calculating int(24//1.6)

**Comment by singh96aman** [comment]
Instead of floor division (a//b), propose we use ceil division (ceil(a/b)

Pull Request - https://github.com/baler-collaboration/baler/pull/263
