### ISSUE TITLE
Decoder Fails for large files

### ISSUE THREAD

**Issue by singh96aman** [baler-collaboration/baler#266]
**Describe the bug**
For large files (~1GB+), Decoder seems to running out of memory while training on the CPU. This either happens 1) While Decoding large files for the compressed data and/or 2) While renormalizing decoded output. 

**To Reproduce**
Try Decompressing any large file (~1GB+) on the CPU

**Screenshot**
Attached
![Screenshot 2023-06-02 130640](https://github.com/baler-collaboration/baler/assets/14856694/09c3a2be-d8aa-477c-a7f6-fd3a383c3ac1)

**Comment by fritjof-b** [comment]
I'm assuming the PR (#267)  I just merged fixed this. If you put the issue name in the commit message or PR message it will autoclose the corresponding issue.

See this https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

Nonetheless, is this done?

**Comment by singh96aman** [comment]
Yes This is done !
Closed in #267
