### ISSUE TITLE
Homebrew for Baler

### ISSUE THREAD

**Issue by fritjof-b** [baler-collaboration/baler#273]
Considering the current volatile state of Baler and our focus on providing the best experience for macOS users, it would be beneficial to create a Homebrew tap for our project. This would allow our users to easily install and update the software and would enable us to manage updates and versioning more efficiently.

Steps required:

- [x] Create a new GitHub repository: This will be our tap repository. The convention is to name it `homebrew-{tap}`.
- [x] Create a Formula: We'll need to write a Ruby script, a "formula" that instructs Homebrew on how to install our program. It should be stored in the `Formula` directory in our tap repository.
- [ ] ~Install Poetry via our Formula: As our project uses Poetry for dependency management, the formula should include steps to install Poetry and then use it to install our project and its dependencies.~
- [ ] Push the Formula to our Tap Repository: Once the formula is tested and working correctly, it should be pushed to the tap repository.
- [ ] Inform Users: We need to update our README and other relevant documentation to inform users of this new installation method.

When we've achieved further stability, we can look into migrating from our tap into brew core. I'd like to invite everyone to discuss this proposal and share any concerns, suggestions, or thoughts.

Further reading:

- [Taps in Brew](https://docs.brew.sh/Taps)
- [Ruby for Brew](https://rubydoc.brew.sh)
- [Acceptable Formulae](https://docs.brew.sh/Acceptable-Formulae)

**Comment by exook** [comment]
This is a great outline, nice work!

**Comment by fritjof-b** [comment]
I've decided against using `poetry` for brew, since brew manages its own python virtual envs. Luckily `poetry` can generate `requirements.txt` files from `pyproject.toml`. We need to keep that up-do-date.
