### ISSUE TITLE
HEP test project as per README gives an error

### ISSUE THREAD

**Issue by urania277** [baler-collaboration/baler#290]
How to reproduce: 

Follow the README instructions for python, namely:

`poetry run python -m baler --project CMS_workspace CMS_project_v1 --mode train  
`
then

`poetry run python -m baler --project CMS_workspace CMS_project_v1 --mode compress
`

Leads to: 

> Traceback (most recent call last):
>   File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/Users/urania277/Work/BALER-GIT/baler/baler/__main__.py", line 3, in <module>
>     main()
>   File "/Users/urania277/Work/BALER-GIT/baler/baler/baler.py", line 50, in main
>     perform_compression(output_path, config, verbose)
>   File "/Users/urania277/Work/BALER-GIT/baler/baler/baler.py", line 277, in perform_compression
>     np.save(file=f_deltas, arr=error_bound_deltas)
>   File "<__array_function__ internals>", line 200, in save
>   File "/Users/urania277/Library/Caches/pypoetry/virtualenvs/baler-6JwR2JoC-py3.10/lib/python3.10/site-packages/numpy/lib/npyio.py", line 521, in save
>     arr = np.asanyarray(arr)
> ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (1016,) + inhomogeneous part.
> 

The solution suggested by @singh96aman and tested by Ido Elbaz (coming soon on this GitHub) is to downgrade numpy version (1.24.3 -> 1.23.5). 

Should we propagate this change in the requirements.txt file?  

https://github.com/baler-collaboration/baler/blob/9d9e2da9178b1a5d5ae9458d315521beda1a59ac/requirements.txt#L282

**Comment by fritjof-b** [comment]
Numpy version was fixed to 1.23.5 in #291 , could you try it again? If it works we can close this issue and open another for the error related to the specific numpy version.

**Comment by urania277** [comment]
This is fixed now, thanks!
