### ISSUE TITLE
Global flag for error-bound compression

### ISSUE THREAD

**Issue by urania277** [baler-collaboration/baler#295]
Hi @singh96aman, 

we can't figure out how to make error-bound compression optional using the flags below. 

https://github.com/baler-collaboration/baler/blob/c11e6fe7e424c9f3ce605cba0886305cf0862aa8/workspaces/CMS_workspace/CMS_project_v1/config/CMS_project_v1_config.py#L16C37-L16C37

Could we have a global true/false flag for turning this off if the user doesn't wish to use it?  

Thanks!

**Comment by singh96aman** [comment]
We've a global true/false flag ([here](https://github.com/singh96aman/baler/blob/d68c3fa2b883a3ecdeff85d348c5bb151685b9ad/workspaces/CFD_workspace/CFD_project_animation/config/CFD_project_animation_config.py#L29)). 

It's been set to true which in hindsight seems wrong. I'll raise a PR to make this false by default

**Comment by fritjof-b** [comment]
This is complete with #294
