### ISSUE TITLE
Baler/poetry incompatible with newer Python versions (>3.11)

### ISSUE THREAD

**Issue by urania277** [baler-collaboration/baler#310]
When following the README, the following message appears if the version of Python is newer than 3.11:

```
The currently activated Python version 3.11.6 is not supported by the project (>=3.8, <3.11).
Trying to find and use a compatible version. 
```

Things will still work if the user has an older version of Python installed, but I'm wondering whether we should upgrade the requirements here (and I am not necessarily an expert on how to do so).

**Comment by fritjof-b** [comment]
@urania277 

I believe we set the `Python` version because of an underlying problem--that we have control over--with one of the dependencies (might have been `numpy`).

Is there a specific reason you want to upgrade the version? Are you having trouble running Baler?

**Comment by urania277** [comment]
Sorry to get back to this so late - I don't think this is necessarily a problem, just wondering how often we should bump the python/numpy versions. Let's close this and discuss elsewhere.

**Comment by fritjof-b** [comment]
No worries, let me know if I can assist with any other thoughts!
