### ISSUE TITLE
Add the Numba, cupy support for Baler

### ISSUE THREAD

**Issue by neogyk** [baler-collaboration/baler#325]
Add the jit compilation using [Numba](https://numba.readthedocs.io/en/stable/user/jit.html) and [cupy](https://docs.cupy.dev/en/stable/index.html) for Baler.

**Comment by exook** [comment]
This was just merged to the new main branch :)

**Comment by exook** [comment]
Running with the new jit decorators causes a lot of terminal output regarding "nopython=False" and functions being compiled in "object mode" without "forceobj=True"

**Comment by exook** [comment]
I changed "nopython=False" to "forceobj=True"
