### ISSUE TITLE
Documentation for developers

### ISSUE THREAD

**Issue by urania277** [baler-collaboration/baler#335]
When a new developer joins, they can't easily find in the documentation how to test their changes. 
We could have a README for developers, I volunteer if someone instructs me as it's been a while since I made changes :)

**Comment by fritjof-b** [comment]
I wrote some scripts located in `bin/` that should be run from the root like so 

```sh
./bin/tests.sh
```

All dependencies should be installed prior to doing this. Also, we should prompt developers to add tests for the code that they write. I'm not sure if we do this.
